import DeskAuth
import Foundation
import Testing
@testable import DeskPerpl

/// Pinned to reference/perpl/vectors.mjs, generated by the Node implementation that was
/// proven against Perpl's live testnet. The signing key is Mera's published Ed25519
/// seed, so PRF output through signature is one reproducible chain.
@Suite("Perpl canonical strings")
struct PerplCanonicalTests {
    struct Vectors: Decodable {
        struct Rest: Decodable {
            let method: String, target: String, body: String
            let canonical: String, signature: String
        }
        struct SignIn: Decodable { let canonical: String, signature: String }
        let chainId: UInt64
        let ed25519Seed: String
        let timestamp: String
        let nonce: String
        let emptyBodySha256: String
        let rest: [Rest]
        let signin: SignIn
    }

    let vectors: Vectors
    let signer: PerplSigner
    let stamp: RequestStamp

    init() throws {
        let url = try #require(Bundle.module.url(forResource: "CanonicalVectors", withExtension: "json"))
        vectors = try JSONDecoder().decode(Vectors.self, from: Data(contentsOf: url))
        signer = PerplSigner(seed: SecureBytes(Data(hex: vectors.ed25519Seed)))
        stamp = RequestStamp(
            timestampMilliseconds: try #require(Int64(vectors.timestamp)),
            nonce: vectors.nonce)
    }

    @Test("REST canonical strings match the reference")
    func restCanonical() throws {
        for vector in vectors.rest {
            let canonical = PerplCanonical.rest(
                chainID: vectors.chainId,
                method: vector.method,
                target: vector.target,
                body: Data(vector.body.utf8),
                stamp: stamp)
            #expect(canonical == vector.canonical, "\(vector.method) \(vector.target)")
        }
    }

    // CryptoKit signs Ed25519 with a hedged nonce, so our signature is never byte-equal
    // to the reference's. Cross-verification is the stronger check anyway: it proves
    // both implementations agree on the message and the key.
    @Test("the reference signatures verify under our key")
    func referenceSignaturesVerify() throws {
        for vector in vectors.rest {
            let canonical = PerplCanonical.rest(
                chainID: vectors.chainId,
                method: vector.method,
                target: vector.target,
                body: Data(vector.body.utf8),
                stamp: stamp)
            #expect(try signer.verify(vector.signature, over: canonical),
                    "\(vector.method) \(vector.target)")
        }
    }

    @Test("our signatures verify, and are hedged rather than deterministic")
    func ourSignaturesVerify() throws {
        for vector in vectors.rest {
            let canonical = PerplCanonical.rest(
                chainID: vectors.chainId,
                method: vector.method,
                target: vector.target,
                body: Data(vector.body.utf8),
                stamp: stamp)
            let signature = try signer.sign(canonical)
            #expect(try signer.verify(signature, over: canonical))
            #expect(signature != vector.signature)
            #expect(Base64URL.decode(signature)?.count == 64)
        }
    }

    @Test("a signature does not verify over a different string")
    func signatureIsBoundToItsString() throws {
        let canonical = PerplCanonical.signIn(chainID: 10143, stamp: stamp)
        let signature = try signer.sign(canonical)
        let tampered = PerplCanonical.signIn(chainID: 143, stamp: stamp)
        #expect(try !signer.verify(signature, over: tampered))
        #expect(try !signer.verify(signature, over: canonical + "\n"))
        #expect(try !signer.verify("not-base64url!!", over: canonical))
    }

    @Test("the socket sign-in string and signature match the reference")
    func signIn() throws {
        let canonical = PerplCanonical.signIn(chainID: vectors.chainId, stamp: stamp)
        #expect(canonical == vectors.signin.canonical)
        #expect(try signer.verify(vectors.signin.signature, over: canonical))
    }

    @Test("an empty body hashes to sha256 of zero bytes")
    func emptyBodyHash() {
        #expect(PerplCanonical.sha256Hex(Data()) == vectors.emptyBodySha256)
    }

    @Test("the canonical string has no trailing newline")
    func noTrailingNewline() {
        let canonical = PerplCanonical.rest(
            chainID: 10143, method: "GET", target: "/v1/x", body: Data(), stamp: stamp)
        #expect(!canonical.hasSuffix("\n"))
        #expect(canonical.filter { $0 == "\n" }.count == 5)
        #expect(PerplCanonical.signIn(chainID: 10143, stamp: stamp)
            .filter { $0 == "\n" }.count == 3)
    }

    @Test("the query is signed byte-exact, so re-encoding breaks it")
    func querySignedVerbatim() {
        let withQuery = PerplCanonical.rest(
            chainID: 10143, method: "GET", target: "/v1/trading/fills?page=2&count=100",
            body: Data(), stamp: stamp)
        let reordered = PerplCanonical.rest(
            chainID: 10143, method: "GET", target: "/v1/trading/fills?count=100&page=2",
            body: Data(), stamp: stamp)
        #expect(withQuery != reordered)
    }

    @Test("the public key is the one Mera derives")
    func publicKey() throws {
        #expect(try signer.publicKeyHex()
            == "0x89684d872dd939e6c13b2c9d501465bdfe3546a81d32c2889dca5b6847046100")
    }

    @Test("headers carry the same stamp the signature was made over")
    func headersMatchStamp() throws {
        let canonical = PerplCanonical.signIn(chainID: 10143, stamp: stamp)
        let headers = PerplHeaders.signed(
            apiKey: "abc", stamp: stamp, signature: try signer.sign(canonical))
        #expect(headers[PerplHeaders.timestamp] == vectors.timestamp)
        #expect(headers[PerplHeaders.nonce] == vectors.nonce)
        #expect(headers[PerplHeaders.apiKey] == "abc")
    }

    @Test("a generated stamp is fresh and unpadded")
    func generatedStamp() {
        let first = RequestStamp.generate()
        let second = RequestStamp.generate()
        #expect(first.nonce != second.nonce)
        #expect(!first.nonce.contains("="))
        #expect(!first.nonce.contains("+"))
        #expect(!first.nonce.contains("/"))
        #expect(Base64URL.decode(first.nonce)?.count == 16)
        #expect(first.timestampMilliseconds > 1_700_000_000_000)
    }
}

extension Data {
    init(hex: String) {
        precondition(hex.count % 2 == 0, "hex literal has an odd length")
        var bytes = [UInt8]()
        var index = hex.startIndex
        while index < hex.endIndex {
            let next = hex.index(index, offsetBy: 2)
            guard let byte = UInt8(hex[index..<next], radix: 16) else {
                preconditionFailure("not hex: \(hex[index..<next])")
            }
            bytes.append(byte)
            index = next
        }
        self.init(bytes)
    }
}
