// Cross-check vectors for DeskChain's EIP-712 encoder, generated by viem.
//
// Every case here is one the Swift got wrong before the DeskChain audit of 13 September:
// integer widths, signed integers, bytesN, nested arrays and zero-padded hex. The point
// is that the expected values come from the reference implementation rather than from
// the implementation being tested.
//
//   node reference/perpl/eip712-vectors.mjs > Tests/DeskChainTests/EIP712Vectors.json
import { createRequire } from "node:module";
const require = createRequire(import.meta.url);
const { hashStruct } = require("/Users/hi/hackatons/recourse/web/node_modules/viem");

const cases = [
  ["uint8 at its ceiling", "A(uint8 x)", { x: 255n }],
  ["uint8 over its ceiling", "A(uint8 x)", { x: 256n }],
  ["uint64 at its ceiling", "A(uint64 x)", { x: 18446744073709551615n }],
  ["int256 minus one", "A(int256 x)", { x: -1n }],
  ["int128 negative", "A(int128 x)", { x: -12345n }],
  ["int128 at its floor", "A(int128 x)", { x: -170141183460469231731687303715884105728n }],
  ["int128 at its ceiling", "A(int128 x)", { x: 170141183460469231731687303715884105727n }],
  ["int128 under its floor", "A(int128 x)", { x: -170141183460469231731687303715884105729n }],
  ["bytes4", "A(bytes4 x)", { x: "0xdeadbeef" }],
  ["bytes8", "A(bytes8 x)", { x: "0x0011223344556677" }],
  ["bytes32", "A(bytes32 x)", { x: "0x" + "11".repeat(32) }],
  ["nested array", "A(uint256[2][2] xs)", { xs: [[1n, 2n], [3n, 4n]] }],
  ["zero padded hex", "A(uint256 x)", { x: 1n }],
  ["empty bytes", "A(bytes b)", { b: "0x" }],
  ["even bytes", "A(bytes b)", { b: "0xabcd" }],
  ["unicode string", "A(string s)", { s: "héllo 🚀 ünïcode" }],
  ["bool", "A(bool b)", { b: true }],
];

const parse = (signature) => {
  const name = signature.slice(0, signature.indexOf("("));
  const inner = signature.slice(signature.indexOf("(") + 1, -1);
  const fields = inner.split(",").map((part) => {
    const gap = part.lastIndexOf(" ");
    return { type: part.slice(0, gap), name: part.slice(gap + 1) };
  });
  return { name, fields };
};

const stringify = (value) =>
  typeof value === "bigint" ? value.toString()
  : Array.isArray(value) ? value.map(stringify)
  : value;

const out = [];
for (const [label, signature, message] of cases) {
  const { name, fields } = parse(signature);
  const types = { [name]: fields };
  let structHash = null;
  let rejected = null;
  try {
    structHash = hashStruct({ data: message, primaryType: name, types });
  } catch (error) {
    rejected = error.name ?? "error";
  }
  const encoded = {};
  for (const [key, value] of Object.entries(message)) encoded[key] = stringify(value);
  out.push({ label, encodeType: signature, types, message: encoded, structHash, rejected });
}
console.log(JSON.stringify(out, null, 1));
